// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUODfUwk3u5JGEvTs0Y9O6B7L9CZlAcJs',
    appId: '1:44460991792:web:d9cc96a2fc98c05a99d4f5',
    messagingSenderId: '44460991792',
    projectId: 'takhleeqish',
    authDomain: 'takhleeqish.firebaseapp.com',
    storageBucket: 'takhleeqish.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5OzkdNIeRWs9AvQIktUcrXP6XU-Wq8U',
    appId: '1:44460991792:android:a2b75c9a4a34b4c199d4f5',
    messagingSenderId: '44460991792',
    projectId: 'takhleeqish',
    storageBucket: 'takhleeqish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOFMQPsy-TGJMorBHgM6rIlTWgwlk2DI',
    appId: '1:44460991792:ios:8b81ed7884b169d499d4f5',
    messagingSenderId: '44460991792',
    projectId: 'takhleeqish',
    storageBucket: 'takhleeqish.appspot.com',
    iosBundleId: 'com.example.takhleekish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOFMQPsy-TGJMorBHgM6rIlTWgwlk2DI',
    appId: '1:44460991792:ios:f705ef60b3a85ac299d4f5',
    messagingSenderId: '44460991792',
    projectId: 'takhleeqish',
    storageBucket: 'takhleeqish.appspot.com',
    iosBundleId: 'com.example.takhleekish.RunnerTests',
  );
}
